baseURL = "https://mentalreaper.github.io/"
languageCode = "en-gb"
title = "Alexander JD Conn"
theme = "PaperMod"

[[menu.main]]
name = "~/portfolio"
identifier = "~/portfolio"
url = "/portfolio"
weight = 5

[[menu.main]]
name = "~/blog"
identifier = "~/blog"
url = "/blog"

[[menu.main]]
name = "~/links"
identifier = "~/links"
url = "https://linktr.ee/alexanderconn"